# Generated by Django 4.2.8 on 2023-12-11 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='complete',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
