# Generated by Django 4.2.8 on 2023-12-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='redeem',
            field=models.IntegerField(default=0),
        ),
    ]
