# Generated by Django 4.2.8 on 2023-12-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reward_redeem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='redeem',
        ),
        migrations.AddField(
            model_name='student',
            name='redeem',
            field=models.IntegerField(default=0),
        ),
    ]
